spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/meedding
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

domain:
  https://meedding.kro.kr
kakao:
  clientId: 9ab70c68899154e1060b5e2979b54d92
  redirectUri: https://meedding.kro.kr/auth/kakao/callback