spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/meedding
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

domain:
  http://localhost:8080

kakao:
  clientId: 9ab70c68899154e1060b5e2979b54d92
  redirectUri: http://localhost:8080/auth/kakao/callback
cosKey: cos1234