spring:
  datasource:
    url: jdbc:mariadb://meedding.ctoilrrq7tkn.ap-northeast-2.rds.amazonaws.com/Meedding
    username: junbeom_kang
    password: wnsqja12
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  web: debug
  org.hibernate.SQL: #debug

domain:
  https://meedding.kro.kr

kakao:
  clientId: 9ab70c68899154e1060b5e2979b54d92
  redirectUri: https://meedding.kro.kr/api/auth/kakao/callback
cosKey: cos1234

openvidu:
  url: https://meedding-openvidu.kro.kr/
  secret: MY_SECRET